# Generated by Django 3.2.9 on 2021-11-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
    ]
